#!/bin/bash
#I wrote this for testing, but realized it's exactly what true and false do!
if [ "$#" -ne 1 ]
then
    echo "Usage: ./conditional_exit <input>"
    echo "If input is 0, exit 0, else exit 1."
    exit 1
fi

if [[ "$1" = 0 ]]; then
    exit 0
else
    exit 1
fi
