#!/bin/bash
#Variable quoting error due to Word splitting.

SECRET_PASSWORD="Open Sesame"

echo "Enter the secret password for \$1000000"
echo

if test $SECRET_PASSWORD = "Open Sesame"
then
    echo 'Here is $1000000'
else
    echo "I'm sorry, you failed the test"
fi

sleep 3

echo
echo "Without double quotes, \$SECRET_PASSWORD was expanded to two"
echo "arguments. The line: test <arg1> <arg2> = \"Open Sesame\""
echo "failed with exit status 2, so the conditional ran the else"
echo "clause."
echo
echo "Correct usage:"
echo 'if test "$SECRET_PASSWORD" = "Open Sesame"'
echo

if test "$SECRET_PASSWORD" = "Open Sesame"
then
    echo 'Here is $1000000'
else
    echo "I'm sorry, you failed the test"
fi

